### ISSUE TITLE
How to run pretrained model VQA-X with single image in Google Colab

### ISSUE THREAD

**Issue by MachinicGlitch** [fawazsammani/nlxgpt#1]
Hi!

I am wanting to run the pretrained VQAX_p model (the same one that is used in the 'Explanations with Natural Text' Hugging Face demo).  I have the project files and dependencies all imported into Google Colab, but I am unsure which files/functions I should be using in order to get explanation on one single image.

**Comment by MachinicGlitch** [comment]
Yes I did figure it out, feel blind in hindsight but the hugging face app actually has an attached codebase with exactly what I was looking for:

https://huggingface.co/spaces/Fawaz/nlx-gpt/tree/main 

Should be what you need here in app.py, and the VQAX_p directory has the pretrained model.

**Comment by fawazsammani** [comment]
Dear @MachinicGlitch and @Ellyuca ,
I'm really sorry for the late reply. I was pressured with work in the past month. 

It's good that you figured it out!
Let me know if there are other problems.

**Comment by Ellyuca** [comment]
Hi @fawazsammani,
I am trying to run the pretrained model on the ACT_X using a single image.
So given an image, I want to get the activity recognition label and the explanation for it.
@MachinicGlitch kindly pointed me to the code used for the VQAX demo.

I was wondering how can I adapt that code for the ACT_X task? Can I just use it as it is and have the question be an empty string (something like "")? Do you perhaps have a tutorial/demo for the ACTX as well?

Thank you for your time and any tips and advice you can give me.

PS: @MachinicGlitch  thank you as well.

**Comment by Ellyuca** [comment]
Dear @fawazsammani,

Thank you! that will help me out a lot! 
I really appreciate it!

Best wishes!

**Comment by fawazsammani** [comment]
@Ellyuca you can find it here: https://huggingface.co/spaces/Fawaz/nlx_gpt_action

**Comment by Ellyuca** [comment]
@fawazsammani  Thanks a lot!!!
