### ISSUE TITLE
GPU and Train time

### ISSUE THREAD

**Issue by BetterZH** [fawazsammani/nlxgpt#11]
Thanks for your excellent work.
For NLE models on different datasets (VQA-X, ACT-X, e-SNLI-VE), how many GPUs are required for the pre training and finetune stages？And how many hours are required for the pretraining and finetune stages?

**Comment by fawazsammani** [comment]
Hi. If I remember correctly, the pretraining was done on 3 GPUs for around 2 days. For finetuning, one GPU is enough. It takes a few hours (depending on the dataset - VQAX can finish in 2-3 hours while e-SNLI-VE takes longer, around 6 hours) to finish. 

Feel free to open this issue again if you have further questions.
