### ISSUE TITLE
Problems about reproducing the same VQA-X filtered scores reported in paper

### ISSUE THREAD

**Issue by kaipo-chang** [fawazsammani/nlxgpt#7]
Hi @fawazsammani,

Thanks for your excellent work. I am very appreciated your work! However, I failed to reproduce the same scores on VQA-X datasets, and thus I want to check whether I was on the correct way about the model usage in [models](https://github.com/fawazsammani/nlxgpt#models) section. 

Are the models in [models](https://github.com/fawazsammani/nlxgpt#models) section the checkpoints that could have the approximated performance reported on paper? In my experiments, [the pretrained vqaX checkpoint model](https://drive.google.com/drive/folders/1Bfc__0HRzYPyvRe0Ur_oSbhO8dSavT4e) could only achieve 103 on filtered CIDEr. Or, should I use [the checkpoints](https://drive.google.com/drive/folders/1_3xVoMJwV98j7vUxEEJsQ0LGqFGtfkca) to reproduce? Could you please give me some instructions to reproduce the scores on your reported paper?

**Comment by fawazsammani** [comment]
Hi @kaipo-chang 
Are you changing any of the hyperparameters during training? Are you initializing with the pretrained model? Are you running the `filter_and_get_scores` function? Are you using the coco-caption i indicated in the readme? 

I recommend you first use the checkpoint I provided and see if you can get the scores reported in the paper. Or you can directly provide the json output result I provided. If you do not get the correct scores, then there is probably a different coco-caption you are using?

**Comment by kaipo-chang** [comment]
Thank you for your rapid reply. After your kindly reminder, I found that I forget to set `finetuned_pretrained` to True. Therefore, the distilGPT2 is initialized from Huggingface. Sorry for making this stupid error. 

On the other hand, I would like to ask you why the clip-encoder would be fixed during finetuning. Do you have done the related experiments?

**Comment by fawazsammani** [comment]
@kaipo-chang finetuning clip is not that safe and easy as you expect. You need to follow carefully very specific guides and hyperparameters in order for it to work. And above all that it may not work at the end. You can find these guides and hyperparameters somewhere in one of the issues of the clip github repo i think. I remember following them, and it ended up not working at all. Also, I think keeping a strong modality fixed (image features) and training the other (text) has a good impact (topic of the popular [LiT](https://arxiv.org/abs/2111.07991) paper). Also, training is much faster. You may try finetuning CLIP, and would love to hear from you if you could make it work!

Regards
